agents:
  queue: "k8s-builders"

steps:
  - label: Terraform Apply and Destroy Private
    key: apply-destroy-private
    command: .buildkite/scripts/apply.sh --TF_DIR examples/private --PREFIX rp-private
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - json-key: .
              secret-id: sdlc/prod/buildkite/devex_gcp_creds_base64
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION

  - label: Terraform Apply and Destroy VPC Public
    key: apply-destroy-public-vpc
    command: .buildkite/scripts/apply.sh --TF_DIR examples/public-vpc --PREFIX rp-pub-vpc
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - json-key: .
              secret-id: sdlc/prod/buildkite/devex_gcp_creds_base64
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION

  - label: Terraform Apply and Destroy VPC Public IS4
    key: apply-destroy-public-vpc-is4
    command: .buildkite/scripts/apply.sh --TF_DIR examples/public-vpc-is4 --PREFIX rp-pub-vpc-is4
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - json-key: .
              secret-id: sdlc/prod/buildkite/devex_gcp_creds_base64
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION

  - label: Terraform Apply and Destroy Simple
    key: apply-destroy-simple
    command: .buildkite/scripts/apply.sh --TF_DIR examples/simple --PREFIX rp-simple
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - json-key: .
              secret-id: sdlc/prod/buildkite/devex_gcp_creds_base64
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION

  - label: Terraform Apply and Destroy Tiered Storage
    key: apply-destroy-tiered-storage
    command: .buildkite/scripts/apply.sh --TF_DIR examples/tiered_storage --PREFIX rp-tiered-storage
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - json-key: .
              secret-id: sdlc/prod/buildkite/devex_gcp_creds_base64
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION

  - label: Terraform Apply and Destroy Private VPC
    key: apply-destroy-pvt-vpc
    command: .buildkite/scripts/apply.sh --TF_DIR examples/private-vpc --PREFIX rp-pvt-vpc
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - json-key: .
              secret-id: sdlc/prod/buildkite/devex_gcp_creds_base64
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION

  - label: Terraform Apply and Destroy Private VPC No Zone
    key: apply-destroy-pvt-vpc-no-zone
    command: .buildkite/scripts/apply.sh --TF_DIR examples/private-vpc-no-zone --PREFIX rp-pvt-nzone
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - json-key: .
              secret-id: sdlc/prod/buildkite/devex_gcp_creds_base64
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: Terraform Apply and Destroy Private VPC Connect
    key: apply-destroy-pvt-vpc-connect
    command: .buildkite/scripts/apply.sh --TF_DIR examples/private-with-connect --PREFIX rp-pvt-cnct
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - json-key: .
              secret-id: sdlc/prod/buildkite/devex_gcp_creds_base64
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
